// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const agentExists = `-- name: AgentExists :one
SELECT EXISTS (SELECT 1 FROM agents WHERE workspace_id = $1 AND id = $2)
`

type AgentExistsParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) AgentExists(ctx context.Context, arg AgentExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentExists, arg.WorkspaceID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, workspace_id, name, description, provider, model, system_prompt, output_schema, enabled, version, created_by, created_at, strategy, ci_fail_on, repo_intel FROM agents WHERE workspace_id = $1 AND id = $2
`

type GetAgentParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.WorkspaceID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.OutputSchema,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Strategy,
		&i.CiFailOn,
		&i.RepoIntel,
	)
	return i, err
}

const getAgentVersion = `-- name: GetAgentVersion :one
SELECT v.agent_id, v.version, v.config_json, v.created_at
FROM agent_versions v
JOIN agents a ON a.id = v.agent_id
WHERE a.workspace_id = $1 AND v.agent_id = $2 AND v.version = $3
`

type GetAgentVersionParams struct {
	WorkspaceID uuid.UUID
	AgentID     uuid.UUID
	Version     int32
}

// One config snapshot, if the agent is in the workspace.
func (q *Queries) GetAgentVersion(ctx context.Context, arg GetAgentVersionParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentVersion, arg.WorkspaceID, arg.AgentID, arg.Version)
	var i AgentVersion
	err := row.Scan(
		&i.AgentID,
		&i.Version,
		&i.ConfigJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentSkillBodies = `-- name: ListAgentSkillBodies :many
SELECT s.name, s.body
FROM agent_skills l
JOIN skills s ON s.id = l.skill_id
WHERE l.agent_id = $1 AND s.enabled AND btrim(s.body, E' \t\n\r') <> ''
ORDER BY l."order", l.skill_id
`

type ListAgentSkillBodiesRow struct {
	Name string
	Body string
}

// What a review's prompt gets from the agent's skills: the enabled ones with
// a body that isn't blank, in the agent's order.
func (q *Queries) ListAgentSkillBodies(ctx context.Context, agentID uuid.UUID) ([]ListAgentSkillBodiesRow, error) {
	rows, err := q.db.Query(ctx, listAgentSkillBodies, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSkillBodiesRow
	for rows.Next() {
		var i ListAgentSkillBodiesRow
		if err := rows.Scan(&i.Name, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSkills = `-- name: ListAgentSkills :many
SELECT l.skill_id, l."order"
FROM agent_skills l
JOIN skills s ON s.id = l.skill_id
WHERE l.agent_id = $1
ORDER BY l."order", l.skill_id
`

type ListAgentSkillsRow struct {
	SkillID uuid.UUID
	Order   int32
}

// The skills linked to an agent, in the order the agent uses them.
func (q *Queries) ListAgentSkills(ctx context.Context, agentID uuid.UUID) ([]ListAgentSkillsRow, error) {
	rows, err := q.db.Query(ctx, listAgentSkills, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSkillsRow
	for rows.Next() {
		var i ListAgentSkillsRow
		if err := rows.Scan(&i.SkillID, &i.Order); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentVersions = `-- name: ListAgentVersions :many
SELECT agent_id, version, config_json, created_at FROM agent_versions WHERE agent_id = $1 ORDER BY version DESC
`

// An agent's config history, newest first.
func (q *Queries) ListAgentVersions(ctx context.Context, agentID uuid.UUID) ([]AgentVersion, error) {
	rows, err := q.db.Query(ctx, listAgentVersions, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentVersion
	for rows.Next() {
		var i AgentVersion
		if err := rows.Scan(
			&i.AgentID,
			&i.Version,
			&i.ConfigJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, workspace_id, name, description, provider, model, system_prompt, output_schema, enabled, version, created_by, created_at, strategy, ci_fail_on, repo_intel FROM agents WHERE workspace_id = $1 ORDER BY created_at, id
`

// Oldest first, so the order is stable. (The TS server has no ORDER BY.)
func (q *Queries) ListAgents(ctx context.Context, workspaceID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Model,
			&i.SystemPrompt,
			&i.OutputSchema,
			&i.Enabled,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Strategy,
			&i.CiFailOn,
			&i.RepoIntel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
