// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents_write.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const countLinkedSkills = `-- name: CountLinkedSkills :one
SELECT count(*) FROM agent_skills WHERE agent_id = $1
`

func (q *Queries) CountLinkedSkills(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkedSkills, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (workspace_id, name, description, provider, model, system_prompt,
                    output_schema, strategy, ci_fail_on, repo_intel, enabled, version, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 1, $12)
RETURNING id, workspace_id, name, description, provider, model, system_prompt, output_schema, enabled, version, created_by, created_at, strategy, ci_fail_on, repo_intel
`

type CreateAgentParams struct {
	WorkspaceID  uuid.UUID
	Name         string
	Description  string
	Provider     string
	Model        string
	SystemPrompt string
	OutputSchema []byte
	Strategy     string
	CiFailOn     string
	RepoIntel    bool
	Enabled      bool
	CreatedBy    *uuid.UUID
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Model,
		arg.SystemPrompt,
		arg.OutputSchema,
		arg.Strategy,
		arg.CiFailOn,
		arg.RepoIntel,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.OutputSchema,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Strategy,
		&i.CiFailOn,
		&i.RepoIntel,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :execrows
DELETE FROM agents WHERE workspace_id = $1 AND id = $2
`

type DeleteAgentParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgent, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAgentVersion = `-- name: InsertAgentVersion :exec
INSERT INTO agent_versions (agent_id, version, config_json) VALUES ($1, $2, $3)
`

type InsertAgentVersionParams struct {
	AgentID    uuid.UUID
	Version    int32
	ConfigJson []byte
}

func (q *Queries) InsertAgentVersion(ctx context.Context, arg InsertAgentVersionParams) error {
	_, err := q.db.Exec(ctx, insertAgentVersion, arg.AgentID, arg.Version, arg.ConfigJson)
	return err
}

const linkSkill = `-- name: LinkSkill :exec
INSERT INTO agent_skills (agent_id, skill_id, "order") VALUES ($1, $2, $3)
ON CONFLICT (agent_id, skill_id) DO UPDATE SET "order" = EXCLUDED."order"
`

type LinkSkillParams struct {
	AgentID uuid.UUID
	SkillID uuid.UUID
	Order   int32
}

func (q *Queries) LinkSkill(ctx context.Context, arg LinkSkillParams) error {
	_, err := q.db.Exec(ctx, linkSkill, arg.AgentID, arg.SkillID, arg.Order)
	return err
}

const lockAgent = `-- name: LockAgent :one
SELECT id, workspace_id, name, description, provider, model, system_prompt, output_schema, enabled, version, created_by, created_at, strategy, ci_fail_on, repo_intel FROM agents WHERE workspace_id = $1 AND id = $2 FOR UPDATE
`

type LockAgentParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// The agent, locked until the transaction ends, so two updates can't both
// read the same version number.
func (q *Queries) LockAgent(ctx context.Context, arg LockAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, lockAgent, arg.WorkspaceID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.OutputSchema,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Strategy,
		&i.CiFailOn,
		&i.RepoIntel,
	)
	return i, err
}

const skillsInWorkspace = `-- name: SkillsInWorkspace :many
SELECT id FROM skills WHERE workspace_id = $1 AND id = ANY($2::uuid[])
`

type SkillsInWorkspaceParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

// Which of the given skill IDs belong to the workspace.
func (q *Queries) SkillsInWorkspace(ctx context.Context, arg SkillsInWorkspaceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, skillsInWorkspace, arg.WorkspaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAllSkills = `-- name: UnlinkAllSkills :exec
DELETE FROM agent_skills WHERE agent_id = $1
`

func (q *Queries) UnlinkAllSkills(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkAllSkills, agentID)
	return err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = $2, description = $3, provider = $4, model = $5, system_prompt = $6,
    output_schema = $7, strategy = $8, ci_fail_on = $9, repo_intel = $10,
    enabled = $11, version = $12
WHERE id = $1
RETURNING id, workspace_id, name, description, provider, model, system_prompt, output_schema, enabled, version, created_by, created_at, strategy, ci_fail_on, repo_intel
`

type UpdateAgentParams struct {
	ID           uuid.UUID
	Name         string
	Description  string
	Provider     string
	Model        string
	SystemPrompt string
	OutputSchema []byte
	Strategy     string
	CiFailOn     string
	RepoIntel    bool
	Enabled      bool
	Version      int32
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Model,
		arg.SystemPrompt,
		arg.OutputSchema,
		arg.Strategy,
		arg.CiFailOn,
		arg.RepoIntel,
		arg.Enabled,
		arg.Version,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.OutputSchema,
		&i.Enabled,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Strategy,
		&i.CiFailOn,
		&i.RepoIntel,
	)
	return i, err
}
