// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conventions.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const listConventions = `-- name: ListConventions :many
SELECT id, workspace_id, repo_id, rule, evidence_path, evidence_snippet, confidence, accepted FROM conventions
WHERE workspace_id = $1 AND repo_id = $2
ORDER BY accepted DESC, confidence DESC NULLS LAST, rule, id
`

type ListConventionsParams struct {
	WorkspaceID uuid.UUID
	RepoID      *uuid.UUID
}

// A repository's conventions: accepted first, then the most confident
// (unknown confidence last), then by rule.
func (q *Queries) ListConventions(ctx context.Context, arg ListConventionsParams) ([]Convention, error) {
	rows, err := q.db.Query(ctx, listConventions, arg.WorkspaceID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Convention
	for rows.Next() {
		var i Convention
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RepoID,
			&i.Rule,
			&i.EvidencePath,
			&i.EvidenceSnippet,
			&i.Confidence,
			&i.Accepted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
