// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package postgres

import (
	"context"
)

// iteratorForCopyEdges implements pgx.CopyFromSource.
type iteratorForCopyEdges struct {
	rows                 []CopyEdgesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyEdges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyEdges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RepoID,
		r.rows[0].FromFile,
		r.rows[0].ToFile,
	}, nil
}

func (r iteratorForCopyEdges) Err() error {
	return nil
}

func (q *Queries) CopyEdges(ctx context.Context, arg []CopyEdgesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"file_edges"}, []string{"repo_id", "from_file", "to_file"}, &iteratorForCopyEdges{rows: arg})
}

// iteratorForCopyFileRanks implements pgx.CopyFromSource.
type iteratorForCopyFileRanks struct {
	rows                 []CopyFileRanksParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyFileRanks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyFileRanks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RepoID,
		r.rows[0].FilePath,
		r.rows[0].Pagerank,
		r.rows[0].Hotness,
		r.rows[0].Rank,
		r.rows[0].Percentile,
	}, nil
}

func (r iteratorForCopyFileRanks) Err() error {
	return nil
}

func (q *Queries) CopyFileRanks(ctx context.Context, arg []CopyFileRanksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"file_rank"}, []string{"repo_id", "file_path", "pagerank", "hotness", "rank", "percentile"}, &iteratorForCopyFileRanks{rows: arg})
}

// iteratorForCopyReferences implements pgx.CopyFromSource.
type iteratorForCopyReferences struct {
	rows                 []CopyReferencesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyReferences) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyReferences) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RepoID,
		r.rows[0].FromPath,
		r.rows[0].ToSymbol,
		r.rows[0].Line,
		r.rows[0].ContentHash,
	}, nil
}

func (r iteratorForCopyReferences) Err() error {
	return nil
}

func (q *Queries) CopyReferences(ctx context.Context, arg []CopyReferencesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"references"}, []string{"repo_id", "from_path", "to_symbol", "line", "content_hash"}, &iteratorForCopyReferences{rows: arg})
}

// iteratorForCopySymbols implements pgx.CopyFromSource.
type iteratorForCopySymbols struct {
	rows                 []CopySymbolsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopySymbols) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopySymbols) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RepoID,
		r.rows[0].Path,
		r.rows[0].Name,
		r.rows[0].Kind,
		r.rows[0].Line,
		r.rows[0].EndLine,
		r.rows[0].Exported,
		r.rows[0].Signature,
		r.rows[0].ContentHash,
	}, nil
}

func (r iteratorForCopySymbols) Err() error {
	return nil
}

func (q *Queries) CopySymbols(ctx context.Context, arg []CopySymbolsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"symbols"}, []string{"repo_id", "path", "name", "kind", "line", "end_line", "exported", "signature", "content_hash"}, &iteratorForCopySymbols{rows: arg})
}
