// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexstate.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getIndexState = `-- name: GetIndexState :one
SELECT s.repo_id, s.last_indexed_sha, s.indexer_version, s.status, s.files_indexed, s.files_skipped, s.stats, s.updated_at
FROM repo_index_state s
JOIN repos r ON r.id = s.repo_id
WHERE r.workspace_id = $1 AND s.repo_id = $2
`

type GetIndexStateParams struct {
	WorkspaceID uuid.UUID
	RepoID      uuid.UUID
}

// The repository's code index state, if the repository is in the workspace.
func (q *Queries) GetIndexState(ctx context.Context, arg GetIndexStateParams) (RepoIndexState, error) {
	row := q.db.QueryRow(ctx, getIndexState, arg.WorkspaceID, arg.RepoID)
	var i RepoIndexState
	err := row.Scan(
		&i.RepoID,
		&i.LastIndexedSha,
		&i.IndexerVersion,
		&i.Status,
		&i.FilesIndexed,
		&i.FilesSkipped,
		&i.Stats,
		&i.UpdatedAt,
	)
	return i, err
}
