// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: index_write.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const advanceIndexedSha = `-- name: AdvanceIndexedSha :exec
UPDATE repo_index_state SET last_indexed_sha = $2, updated_at = now() WHERE repo_id = $1
`

type AdvanceIndexedShaParams struct {
	RepoID         uuid.UUID
	LastIndexedSha string
}

func (q *Queries) AdvanceIndexedSha(ctx context.Context, arg AdvanceIndexedShaParams) error {
	_, err := q.db.Exec(ctx, advanceIndexedSha, arg.RepoID, arg.LastIndexedSha)
	return err
}

const clearDeclFiles = `-- name: ClearDeclFiles :exec
UPDATE "references" SET decl_file = NULL WHERE repo_id = $1
`

func (q *Queries) ClearDeclFiles(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDeclFiles, repoID)
	return err
}

type CopyEdgesParams struct {
	RepoID   uuid.UUID
	FromFile string
	ToFile   string
}

type CopyFileRanksParams struct {
	RepoID     uuid.UUID
	FilePath   string
	Pagerank   float64
	Hotness    float64
	Rank       float64
	Percentile int16
}

type CopyReferencesParams struct {
	RepoID      uuid.UUID
	FromPath    string
	ToSymbol    string
	Line        int32
	ContentHash *string
}

type CopySymbolsParams struct {
	RepoID      uuid.UUID
	Path        string
	Name        string
	Kind        string
	Line        *int32
	EndLine     *int32
	Exported    bool
	Signature   *string
	ContentHash *string
}

const deleteEdges = `-- name: DeleteEdges :exec
DELETE FROM file_edges WHERE repo_id = $1
`

func (q *Queries) DeleteEdges(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdges, repoID)
	return err
}

const deleteFileFacts = `-- name: DeleteFileFacts :exec
DELETE FROM file_facts WHERE repo_id = $1
`

func (q *Queries) DeleteFileFacts(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileFacts, repoID)
	return err
}

const deleteFileFactsIn = `-- name: DeleteFileFactsIn :exec
DELETE FROM file_facts WHERE repo_id = $1 AND file_path = ANY($2::text[])
`

type DeleteFileFactsInParams struct {
	RepoID uuid.UUID
	Paths  []string
}

func (q *Queries) DeleteFileFactsIn(ctx context.Context, arg DeleteFileFactsInParams) error {
	_, err := q.db.Exec(ctx, deleteFileFactsIn, arg.RepoID, arg.Paths)
	return err
}

const deleteFileRanks = `-- name: DeleteFileRanks :exec
DELETE FROM file_rank WHERE repo_id = $1
`

func (q *Queries) DeleteFileRanks(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileRanks, repoID)
	return err
}

const deleteReferences = `-- name: DeleteReferences :exec
DELETE FROM "references" WHERE repo_id = $1
`

func (q *Queries) DeleteReferences(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReferences, repoID)
	return err
}

const deleteReferencesFrom = `-- name: DeleteReferencesFrom :exec
DELETE FROM "references" WHERE repo_id = $1 AND from_path = ANY($2::text[])
`

type DeleteReferencesFromParams struct {
	RepoID uuid.UUID
	Paths  []string
}

func (q *Queries) DeleteReferencesFrom(ctx context.Context, arg DeleteReferencesFromParams) error {
	_, err := q.db.Exec(ctx, deleteReferencesFrom, arg.RepoID, arg.Paths)
	return err
}

const deleteRepoMaps = `-- name: DeleteRepoMaps :exec
DELETE FROM repo_map_cache WHERE repo_id = $1
`

func (q *Queries) DeleteRepoMaps(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepoMaps, repoID)
	return err
}

const deleteSymbols = `-- name: DeleteSymbols :exec
DELETE FROM symbols WHERE repo_id = $1
`

func (q *Queries) DeleteSymbols(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSymbols, repoID)
	return err
}

const deleteSymbolsIn = `-- name: DeleteSymbolsIn :exec
DELETE FROM symbols WHERE repo_id = $1 AND path = ANY($2::text[])
`

type DeleteSymbolsInParams struct {
	RepoID uuid.UUID
	Paths  []string
}

func (q *Queries) DeleteSymbolsIn(ctx context.Context, arg DeleteSymbolsInParams) error {
	_, err := q.db.Exec(ctx, deleteSymbolsIn, arg.RepoID, arg.Paths)
	return err
}

const indexBasics = `-- name: IndexBasics :one
SELECT id, owner, name, clone_path, default_branch FROM repos WHERE id = $1
`

type IndexBasicsRow struct {
	ID            uuid.UUID
	Owner         string
	Name          string
	ClonePath     *string
	DefaultBranch string
}

// What indexing a repository needs, or no row when it was deleted.
func (q *Queries) IndexBasics(ctx context.Context, id uuid.UUID) (IndexBasicsRow, error) {
	row := q.db.QueryRow(ctx, indexBasics, id)
	var i IndexBasicsRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.ClonePath,
		&i.DefaultBranch,
	)
	return i, err
}

const indexStateOf = `-- name: IndexStateOf :one
SELECT last_indexed_sha, indexer_version, status, files_indexed, files_skipped
FROM repo_index_state WHERE repo_id = $1
`

type IndexStateOfRow struct {
	LastIndexedSha string
	IndexerVersion int32
	Status         string
	FilesIndexed   int32
	FilesSkipped   int32
}

func (q *Queries) IndexStateOf(ctx context.Context, repoID uuid.UUID) (IndexStateOfRow, error) {
	row := q.db.QueryRow(ctx, indexStateOf, repoID)
	var i IndexStateOfRow
	err := row.Scan(
		&i.LastIndexedSha,
		&i.IndexerVersion,
		&i.Status,
		&i.FilesIndexed,
		&i.FilesSkipped,
	)
	return i, err
}

const insertFileFacts = `-- name: InsertFileFacts :exec
INSERT INTO file_facts (repo_id, file_path, endpoints, crons) VALUES ($1, $2, $3, $4)
`

type InsertFileFactsParams struct {
	RepoID    uuid.UUID
	FilePath  string
	Endpoints []byte
	Crons     []byte
}

func (q *Queries) InsertFileFacts(ctx context.Context, arg InsertFileFactsParams) error {
	_, err := q.db.Exec(ctx, insertFileFacts,
		arg.RepoID,
		arg.FilePath,
		arg.Endpoints,
		arg.Crons,
	)
	return err
}

const lockRepoIndex = `-- name: LockRepoIndex :exec
SELECT pg_advisory_xact_lock(hashtextextended('repo-index:' || $1::text, 0))
`

// Serializes the indexing of one repository until the transaction ends.
func (q *Queries) LockRepoIndex(ctx context.Context, repoID string) error {
	_, err := q.db.Exec(ctx, lockRepoIndex, repoID)
	return err
}

const mapCandidates = `-- name: MapCandidates :many
SELECT s.path, s.signature
FROM symbols s
JOIN file_rank f ON f.repo_id = s.repo_id AND f.file_path = s.path
WHERE s.repo_id = $1 AND s.signature IS NOT NULL
ORDER BY f.rank DESC, s.exported DESC, s.line, s.name, s.path
`

type MapCandidatesRow struct {
	Path      string
	Signature *string
}

// The symbols with a signature, most depended-on file first; then exported
// ones, by line and name, and by path, so ties have one order.
func (q *Queries) MapCandidates(ctx context.Context, repoID uuid.UUID) ([]MapCandidatesRow, error) {
	rows, err := q.db.Query(ctx, mapCandidates, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapCandidatesRow
	for rows.Next() {
		var i MapCandidatesRow
		if err := rows.Scan(&i.Path, &i.Signature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putRepoMap = `-- name: PutRepoMap :exec
INSERT INTO repo_map_cache (repo_id, commit_sha, token_budget, map_text, token_count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (repo_id, commit_sha, token_budget)
DO UPDATE SET map_text = EXCLUDED.map_text, token_count = EXCLUDED.token_count, created_at = now()
`

type PutRepoMapParams struct {
	RepoID      uuid.UUID
	CommitSha   string
	TokenBudget int32
	MapText     string
	TokenCount  int32
}

func (q *Queries) PutRepoMap(ctx context.Context, arg PutRepoMapParams) error {
	_, err := q.db.Exec(ctx, putRepoMap,
		arg.RepoID,
		arg.CommitSha,
		arg.TokenBudget,
		arg.MapText,
		arg.TokenCount,
	)
	return err
}

const resolveDeclFiles = `-- name: ResolveDeclFiles :exec
WITH cand AS (
    SELECT r.id AS ref_id, e.to_file AS decl
    FROM "references" r
    JOIN file_edges e ON e.repo_id = r.repo_id AND e.from_file = r.from_path
    JOIN symbols s ON s.repo_id = r.repo_id AND s.path = e.to_file
                  AND s.name = r.to_symbol AND s.exported = true
    WHERE r.repo_id = $1
    GROUP BY r.id, e.to_file
),
uniq AS (
    SELECT ref_id FROM cand GROUP BY ref_id HAVING count(*) = 1
)
UPDATE "references" r
SET decl_file = c.decl
FROM cand c
JOIN uniq u ON u.ref_id = c.ref_id
WHERE r.id = c.ref_id
`

// A reference names the file it resolves to when the file it is in imports
// exactly one file exporting a symbol of that name; else it stays NULL.
func (q *Queries) ResolveDeclFiles(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resolveDeclFiles, repoID)
	return err
}

const touchIndexState = `-- name: TouchIndexState :exec
UPDATE repo_index_state SET updated_at = now() WHERE repo_id = $1
`

func (q *Queries) TouchIndexState(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchIndexState, repoID)
	return err
}

const upsertIndexState = `-- name: UpsertIndexState :exec
INSERT INTO repo_index_state (repo_id, last_indexed_sha, indexer_version, status, files_indexed, files_skipped, stats, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (repo_id) DO UPDATE
SET last_indexed_sha = EXCLUDED.last_indexed_sha, indexer_version = EXCLUDED.indexer_version,
    status = EXCLUDED.status, files_indexed = EXCLUDED.files_indexed,
    files_skipped = EXCLUDED.files_skipped, stats = EXCLUDED.stats, updated_at = now()
`

type UpsertIndexStateParams struct {
	RepoID         uuid.UUID
	LastIndexedSha string
	IndexerVersion int32
	Status         string
	FilesIndexed   int32
	FilesSkipped   int32
	Stats          []byte
}

func (q *Queries) UpsertIndexState(ctx context.Context, arg UpsertIndexStateParams) error {
	_, err := q.db.Exec(ctx, upsertIndexState,
		arg.RepoID,
		arg.LastIndexedSha,
		arg.IndexerVersion,
		arg.Status,
		arg.FilesIndexed,
		arg.FilesSkipped,
		arg.Stats,
	)
	return err
}
