// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intent.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getPullIntent = `-- name: GetPullIntent :one
SELECT pr_id, intent, in_scope, out_of_scope, confidence, sources, unresolved, head_sha, fingerprint, provider, model, tokens_in, tokens_out, cost_usd, derived_at FROM pr_intent WHERE pr_id = $1
`

// The PR's most recently derived intent, or no row when none exists.
func (q *Queries) GetPullIntent(ctx context.Context, prID uuid.UUID) (PrIntent, error) {
	row := q.db.QueryRow(ctx, getPullIntent, prID)
	var i PrIntent
	err := row.Scan(
		&i.PrID,
		&i.Intent,
		&i.InScope,
		&i.OutOfScope,
		&i.Confidence,
		&i.Sources,
		&i.Unresolved,
		&i.HeadSha,
		&i.Fingerprint,
		&i.Provider,
		&i.Model,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostUsd,
		&i.DerivedAt,
	)
	return i, err
}

const upsertPullIntent = `-- name: UpsertPullIntent :exec
INSERT INTO pr_intent (pr_id, intent, in_scope, out_of_scope, confidence, sources, unresolved,
                       head_sha, fingerprint, provider, model, tokens_in, tokens_out, cost_usd,
                       derived_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13, $14, now())
ON CONFLICT (pr_id) DO UPDATE SET
    intent = EXCLUDED.intent,
    in_scope = EXCLUDED.in_scope,
    out_of_scope = EXCLUDED.out_of_scope,
    confidence = EXCLUDED.confidence,
    sources = EXCLUDED.sources,
    unresolved = EXCLUDED.unresolved,
    head_sha = EXCLUDED.head_sha,
    fingerprint = EXCLUDED.fingerprint,
    provider = EXCLUDED.provider,
    model = EXCLUDED.model,
    tokens_in = EXCLUDED.tokens_in,
    tokens_out = EXCLUDED.tokens_out,
    cost_usd = EXCLUDED.cost_usd,
    derived_at = now()
`

type UpsertPullIntentParams struct {
	PrID        uuid.UUID
	Intent      string
	InScope     []byte
	OutOfScope  []byte
	Confidence  string
	Sources     []byte
	Unresolved  []byte
	HeadSha     *string
	Fingerprint *string
	Provider    *string
	Model       *string
	TokensIn    *int32
	TokensOut   *int32
	CostUsd     *float64
}

// Replaces the PR's stored intent with a newly derived one.
func (q *Queries) UpsertPullIntent(ctx context.Context, arg UpsertPullIntentParams) error {
	_, err := q.db.Exec(ctx, upsertPullIntent,
		arg.PrID,
		arg.Intent,
		arg.InScope,
		arg.OutOfScope,
		arg.Confidence,
		arg.Sources,
		arg.Unresolved,
		arg.HeadSha,
		arg.Fingerprint,
		arg.Provider,
		arg.Model,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostUsd,
	)
	return err
}
