// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (workspace_id, kind, payload, status) VALUES ($1, $2, $3, 'queued') RETURNING id
`

type CreateJobParams struct {
	WorkspaceID uuid.UUID
	Kind        string
	Payload     []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createJob, arg.WorkspaceID, arg.Kind, arg.Payload)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs SET status = $1, finished_at = now(), error = $2 WHERE id = $3
`

type FinishJobParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

// Records how a job ended: done, or failed with its error.
func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob, arg.Status, arg.Error, arg.ID)
	return err
}

const startJob = `-- name: StartJob :exec
UPDATE jobs SET status = 'running', started_at = now(), attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) StartJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startJob, id)
	return err
}
