// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Agent struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	Name         string
	Description  string
	Provider     string
	Model        string
	SystemPrompt string
	OutputSchema []byte
	Enabled      bool
	Version      int32
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
	Strategy     string
	CiFailOn     string
	RepoIntel    bool
}

type AgentVersion struct {
	AgentID    uuid.UUID
	Version    int32
	ConfigJson []byte
	CreatedAt  time.Time
}

type Convention struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	RepoID          *uuid.UUID
	Rule            string
	EvidencePath    *string
	EvidenceSnippet *string
	Confidence      *float64
	Accepted        bool
}

type Finding struct {
	ID                 uuid.UUID
	ReviewID           uuid.UUID
	File               string
	StartLine          int32
	EndLine            int32
	Severity           string
	Category           string
	Title              string
	Rationale          string
	Suggestion         *string
	Confidence         float64
	Kind               string
	TrifectaComponents []byte
	AcceptedAt         *time.Time
	DismissedAt        *time.Time
}

type PrIntent struct {
	PrID        uuid.UUID
	Intent      string
	InScope     []byte
	OutOfScope  []byte
	Confidence  string
	Sources     []byte
	Unresolved  []byte
	HeadSha     *string
	Fingerprint *string
	Provider    *string
	Model       *string
	TokensIn    *int32
	TokensOut   *int32
	CostUsd     *float64
	DerivedAt   time.Time
}

type PullRequest struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	RepoID          uuid.UUID
	Number          int32
	Title           string
	Author          string
	Branch          string
	Base            string
	HeadSha         string
	LastReviewedSha *string
	Additions       int32
	Deletions       int32
	FilesCount      int32
	Status          string
	Body            *string
	OpenedAt        *time.Time
	UpdatedAt       *time.Time
}

type Repo struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Owner         string
	Name          string
	FullName      string
	DefaultBranch string
	ClonePath     *string
	LastPolledAt  *time.Time
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
}

type RepoIndexState struct {
	RepoID         uuid.UUID
	LastIndexedSha string
	IndexerVersion int32
	Status         string
	FilesIndexed   int32
	FilesSkipped   int32
	Stats          []byte
	UpdatedAt      time.Time
}

type Skill struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	Name          string
	Description   string
	Type          string
	Source        string
	Body          string
	Enabled       bool
	Version       int32
	EvidenceFiles []byte
	CreatedAt     time.Time
}

type SkillVersion struct {
	SkillID   uuid.UUID
	Version   int32
	Body      string
	CreatedAt time.Time
	Message   *string
}
