// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pulls_sync.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePullCommits = `-- name: DeletePullCommits :exec
DELETE FROM pr_commits WHERE pr_id = $1
`

func (q *Queries) DeletePullCommits(ctx context.Context, prID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePullCommits, prID)
	return err
}

const deletePullFiles = `-- name: DeletePullFiles :exec
DELETE FROM pr_files WHERE pr_id = $1
`

func (q *Queries) DeletePullFiles(ctx context.Context, prID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePullFiles, prID)
	return err
}

const insertPullCommit = `-- name: InsertPullCommit :exec
INSERT INTO pr_commits (pr_id, sha, message, author, committed_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertPullCommitParams struct {
	PrID        uuid.UUID
	Sha         string
	Message     string
	Author      string
	CommittedAt *time.Time
}

func (q *Queries) InsertPullCommit(ctx context.Context, arg InsertPullCommitParams) error {
	_, err := q.db.Exec(ctx, insertPullCommit,
		arg.PrID,
		arg.Sha,
		arg.Message,
		arg.Author,
		arg.CommittedAt,
	)
	return err
}

const insertPullFile = `-- name: InsertPullFile :exec
INSERT INTO pr_files (pr_id, path, additions, deletions, patch) VALUES ($1, $2, $3, $4, $5)
`

type InsertPullFileParams struct {
	PrID      uuid.UUID
	Path      string
	Additions int32
	Deletions int32
	Patch     *string
}

func (q *Queries) InsertPullFile(ctx context.Context, arg InsertPullFileParams) error {
	_, err := q.db.Exec(ctx, insertPullFile,
		arg.PrID,
		arg.Path,
		arg.Additions,
		arg.Deletions,
		arg.Patch,
	)
	return err
}

const pullsWithoutStats = `-- name: PullsWithoutStats :many
SELECT number FROM pull_requests
WHERE repo_id = $1 AND additions = 0 AND deletions = 0 AND files_count = 0
ORDER BY number DESC
LIMIT $2
`

type PullsWithoutStatsParams struct {
	RepoID uuid.UUID
	Limit  int32
}

// The numbers of a repository's pull requests with no diff stats yet,
// newest first.
func (q *Queries) PullsWithoutStats(ctx context.Context, arg PullsWithoutStatsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, pullsWithoutStats, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshPull = `-- name: RefreshPull :one
UPDATE pull_requests
SET title = $1, head_sha = $2, status = $3, updated_at = $4,
    opened_at = COALESCE(opened_at, $5), body = $6,
    additions = $7, deletions = $8, files_count = $9
WHERE repo_id = $10 AND number = $11
RETURNING id
`

type RefreshPullParams struct {
	Title      string
	HeadSha    string
	Status     string
	UpdatedAt  *time.Time
	OpenedAt   *time.Time
	Body       *string
	Additions  int32
	Deletions  int32
	FilesCount int32
	RepoID     uuid.UUID
	Number     int32
}

// Saves a pull request's detail from GitHub and returns its ID. Updating the
// row locks it until the transaction ends, so two refreshes can't interleave
// their deletes and inserts of its files and commits.
func (q *Queries) RefreshPull(ctx context.Context, arg RefreshPullParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, refreshPull,
		arg.Title,
		arg.HeadSha,
		arg.Status,
		arg.UpdatedAt,
		arg.OpenedAt,
		arg.Body,
		arg.Additions,
		arg.Deletions,
		arg.FilesCount,
		arg.RepoID,
		arg.Number,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setPullStats = `-- name: SetPullStats :exec
UPDATE pull_requests SET additions = $3, deletions = $4, files_count = $5
WHERE repo_id = $1 AND number = $2
`

type SetPullStatsParams struct {
	RepoID     uuid.UUID
	Number     int32
	Additions  int32
	Deletions  int32
	FilesCount int32
}

func (q *Queries) SetPullStats(ctx context.Context, arg SetPullStatsParams) error {
	_, err := q.db.Exec(ctx, setPullStats,
		arg.RepoID,
		arg.Number,
		arg.Additions,
		arg.Deletions,
		arg.FilesCount,
	)
	return err
}

const upsertPull = `-- name: UpsertPull :exec
INSERT INTO pull_requests (workspace_id, repo_id, number, title, author, branch, base,
                           head_sha, status, opened_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (repo_id, number) DO UPDATE
SET title = EXCLUDED.title, head_sha = EXCLUDED.head_sha, status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at,
    opened_at = COALESCE(pull_requests.opened_at, EXCLUDED.opened_at)
`

type UpsertPullParams struct {
	WorkspaceID uuid.UUID
	RepoID      uuid.UUID
	Number      int32
	Title       string
	Author      string
	Branch      string
	Base        string
	HeadSha     string
	Status      string
	OpenedAt    *time.Time
	UpdatedAt   *time.Time
}

// Adds a pull request from GitHub's list, or updates the fields that change.
// A new one has no diff stats yet: the list leaves them out. opened_at is
// filled in if an earlier sync left it empty.
func (q *Queries) UpsertPull(ctx context.Context, arg UpsertPullParams) error {
	_, err := q.db.Exec(ctx, upsertPull,
		arg.WorkspaceID,
		arg.RepoID,
		arg.Number,
		arg.Title,
		arg.Author,
		arg.Branch,
		arg.Base,
		arg.HeadSha,
		arg.Status,
		arg.OpenedAt,
		arg.UpdatedAt,
	)
	return err
}
