// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pulls.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPull = `-- name: GetPull :one
SELECT id, workspace_id, repo_id, number, title, author, branch, base, head_sha, last_reviewed_sha, additions, deletions, files_count, status, body, opened_at, updated_at FROM pull_requests WHERE workspace_id = $1 AND id = $2
`

type GetPullParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetPull(ctx context.Context, arg GetPullParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPull, arg.WorkspaceID, arg.ID)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepoID,
		&i.Number,
		&i.Title,
		&i.Author,
		&i.Branch,
		&i.Base,
		&i.HeadSha,
		&i.LastReviewedSha,
		&i.Additions,
		&i.Deletions,
		&i.FilesCount,
		&i.Status,
		&i.Body,
		&i.OpenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPullCommits = `-- name: ListPullCommits :many
SELECT sha, message, author, committed_at
FROM pr_commits
WHERE pr_id = $1
ORDER BY committed_at NULLS LAST, sha
`

type ListPullCommitsRow struct {
	Sha         string
	Message     string
	Author      string
	CommittedAt *time.Time
}

func (q *Queries) ListPullCommits(ctx context.Context, prID uuid.UUID) ([]ListPullCommitsRow, error) {
	rows, err := q.db.Query(ctx, listPullCommits, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPullCommitsRow
	for rows.Next() {
		var i ListPullCommitsRow
		if err := rows.Scan(
			&i.Sha,
			&i.Message,
			&i.Author,
			&i.CommittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullFiles = `-- name: ListPullFiles :many
SELECT path, additions, deletions, patch
FROM pr_files
WHERE pr_id = $1
ORDER BY path
`

type ListPullFilesRow struct {
	Path      string
	Additions int32
	Deletions int32
	Patch     *string
}

func (q *Queries) ListPullFiles(ctx context.Context, prID uuid.UUID) ([]ListPullFilesRow, error) {
	rows, err := q.db.Query(ctx, listPullFiles, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPullFilesRow
	for rows.Next() {
		var i ListPullFilesRow
		if err := rows.Scan(
			&i.Path,
			&i.Additions,
			&i.Deletions,
			&i.Patch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPulls = `-- name: ListPulls :many
SELECT p.id, p.number, p.title, p.author, p.branch, p.base, p.head_sha,
       p.last_reviewed_sha, p.additions, p.deletions, p.files_count, p.status,
       p.opened_at, p.updated_at,
       latest.score AS latest_score
FROM pull_requests p
LEFT JOIN LATERAL (
    SELECT r.score
    FROM reviews r
    WHERE r.pr_id = p.id AND r.kind = 'review'
    ORDER BY r.created_at DESC
    LIMIT 1
) latest ON true
WHERE p.repo_id = $1
ORDER BY p.number DESC
`

type ListPullsRow struct {
	ID              uuid.UUID
	Number          int32
	Title           string
	Author          string
	Branch          string
	Base            string
	HeadSha         string
	LastReviewedSha *string
	Additions       int32
	Deletions       int32
	FilesCount      int32
	Status          string
	OpenedAt        *time.Time
	UpdatedAt       *time.Time
	LatestScore     *int32
}

// A repository's pull requests, each with the score of its latest review
// (NULL when never reviewed), newest first. The web app sorts the list itself.
func (q *Queries) ListPulls(ctx context.Context, repoID uuid.UUID) ([]ListPullsRow, error) {
	rows, err := q.db.Query(ctx, listPulls, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPullsRow
	for rows.Next() {
		var i ListPullsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Title,
			&i.Author,
			&i.Branch,
			&i.Base,
			&i.HeadSha,
			&i.LastReviewedSha,
			&i.Additions,
			&i.Deletions,
			&i.FilesCount,
			&i.Status,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.LatestScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repoExists = `-- name: RepoExists :one
SELECT EXISTS (SELECT 1 FROM repos WHERE workspace_id = $1 AND id = $2)
`

type RepoExistsParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) RepoExists(ctx context.Context, arg RepoExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, repoExists, arg.WorkspaceID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
