// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const listRepos = `-- name: ListRepos :many
SELECT id, workspace_id, owner, name, full_name, default_branch, clone_path, last_polled_at, created_by, created_at FROM repos WHERE workspace_id = $1 ORDER BY created_at, id
`

// Oldest first, so the order is stable. (The TS server has no ORDER BY.)
func (q *Queries) ListRepos(ctx context.Context, workspaceID uuid.UUID) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listRepos, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.DefaultBranch,
			&i.ClonePath,
			&i.LastPolledAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
