// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getRepo = `-- name: GetRepo :one
SELECT id, workspace_id, owner, name, full_name, default_branch, clone_path, last_polled_at, created_by, created_at FROM repos WHERE workspace_id = $1 AND id = $2
`

type GetRepoParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetRepo(ctx context.Context, arg GetRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, arg.WorkspaceID, arg.ID)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.ClonePath,
		&i.LastPolledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRepos = `-- name: ListRepos :many
SELECT id, workspace_id, owner, name, full_name, default_branch, clone_path, last_polled_at, created_by, created_at FROM repos WHERE workspace_id = $1 ORDER BY created_at, id
`

// Oldest first, so the order is stable. (The TS server has no ORDER BY.)
func (q *Queries) ListRepos(ctx context.Context, workspaceID uuid.UUID) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listRepos, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.DefaultBranch,
			&i.ClonePath,
			&i.LastPolledAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepoPolled = `-- name: MarkRepoPolled :exec
UPDATE repos SET last_polled_at = now() WHERE id = $1
`

func (q *Queries) MarkRepoPolled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRepoPolled, id)
	return err
}
