// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repointel.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const fileRanks = `-- name: FileRanks :many
SELECT file_path, percentile
FROM file_rank
WHERE repo_id = $1 AND file_path = ANY($2::text[])
ORDER BY file_path
`

type FileRanksParams struct {
	RepoID uuid.UUID
	Paths  []string
}

type FileRanksRow struct {
	FilePath   string
	Percentile int16
}

// How depended-on each of the given files is, as a percentile (0-100), for
// the ones the index ranked.
func (q *Queries) FileRanks(ctx context.Context, arg FileRanksParams) ([]FileRanksRow, error) {
	rows, err := q.db.Query(ctx, fileRanks, arg.RepoID, arg.Paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileRanksRow
	for rows.Next() {
		var i FileRanksRow
		if err := rows.Scan(&i.FilePath, &i.Percentile); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repoMap = `-- name: RepoMap :one
SELECT m.map_text, m.token_count
FROM repo_index_state s
JOIN repo_map_cache m ON m.repo_id = s.repo_id AND m.commit_sha = s.last_indexed_sha
WHERE s.repo_id = $1 AND m.token_budget = $2
`

type RepoMapParams struct {
	RepoID      uuid.UUID
	TokenBudget int32
}

type RepoMapRow struct {
	MapText    string
	TokenCount int32
}

// The repository map cached for the last indexed commit, rendered for a
// token budget.
func (q *Queries) RepoMap(ctx context.Context, arg RepoMapParams) (RepoMapRow, error) {
	row := q.db.QueryRow(ctx, repoMap, arg.RepoID, arg.TokenBudget)
	var i RepoMapRow
	err := row.Scan(&i.MapText, &i.TokenCount)
	return i, err
}
