// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRunTrace = `-- name: GetRunTrace :one
SELECT t.trace
FROM run_traces t
JOIN agent_runs r ON r.id = t.run_id
WHERE r.workspace_id = $1 AND t.run_id = $2
`

type GetRunTraceParams struct {
	WorkspaceID uuid.UUID
	RunID       uuid.UUID
}

// A run's trace document, if the run is in the workspace.
func (q *Queries) GetRunTrace(ctx context.Context, arg GetRunTraceParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRunTrace, arg.WorkspaceID, arg.RunID)
	var trace []byte
	err := row.Scan(&trace)
	return trace, err
}

const listActiveRuns = `-- name: ListActiveRuns :many
SELECT r.id, r.agent_id, a.name AS agent_name, r.ran_at
FROM agent_runs r
LEFT JOIN agents a ON a.id = r.agent_id
WHERE r.workspace_id = $1 AND r.pr_id = $2 AND r.status = 'running'
ORDER BY r.ran_at, r.id
`

type ListActiveRunsParams struct {
	WorkspaceID uuid.UUID
	PrID        *uuid.UUID
}

type ListActiveRunsRow struct {
	ID        uuid.UUID
	AgentID   *uuid.UUID
	AgentName *string
	RanAt     time.Time
}

// A pull request's runs still in progress, oldest first.
func (q *Queries) ListActiveRuns(ctx context.Context, arg ListActiveRunsParams) ([]ListActiveRunsRow, error) {
	rows, err := q.db.Query(ctx, listActiveRuns, arg.WorkspaceID, arg.PrID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRunsRow
	for rows.Next() {
		var i ListActiveRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentName,
			&i.RanAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindings = `-- name: ListFindings :many
SELECT f.id, f.review_id, f.file, f.start_line, f.end_line, f.severity, f.category, f.title, f.rationale, f.suggestion, f.confidence, f.kind, f.trifecta_components, f.accepted_at, f.dismissed_at
FROM findings f
JOIN reviews r ON r.id = f.review_id
WHERE r.pr_id = $1
ORDER BY f.file, f.start_line, f.end_line, f.id
`

// The findings of all of a pull request's reviews, by location.
func (q *Queries) ListFindings(ctx context.Context, prID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindings, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Severity,
			&i.Category,
			&i.Title,
			&i.Rationale,
			&i.Suggestion,
			&i.Confidence,
			&i.Kind,
			&i.TrifectaComponents,
			&i.AcceptedAt,
			&i.DismissedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT r.id, r.pr_id, r.agent_id, r.run_id, a.name AS agent_name, r.kind,
       r.verdict, r.summary, r.score, r.model, r.created_at
FROM reviews r
LEFT JOIN agents a ON a.id = r.agent_id AND a.workspace_id = r.workspace_id
WHERE r.pr_id = $1
ORDER BY r.created_at DESC, r.id
`

type ListReviewsRow struct {
	ID        uuid.UUID
	PrID      uuid.UUID
	AgentID   *uuid.UUID
	RunID     *uuid.UUID
	AgentName *string
	Kind      string
	Verdict   *string
	Summary   *string
	Score     *int32
	Model     *string
	CreatedAt time.Time
}

// A pull request's reviews, newest first, each with the name of the agent
// that wrote it: NULL when that agent was deleted.
func (q *Queries) ListReviews(ctx context.Context, prID uuid.UUID) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrID,
			&i.AgentID,
			&i.RunID,
			&i.AgentName,
			&i.Kind,
			&i.Verdict,
			&i.Summary,
			&i.Score,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT r.id, r.agent_id, a.name AS agent_name, r.provider, r.model, r.status,
       r.error, r.duration_ms, r.tokens_in, r.tokens_out, r.findings_count,
       r.grounding, r.ran_at, r.score, r.blockers
FROM agent_runs r
LEFT JOIN agents a ON a.id = r.agent_id
WHERE r.workspace_id = $1 AND r.pr_id = $2
ORDER BY r.ran_at DESC, r.id
`

type ListRunsParams struct {
	WorkspaceID uuid.UUID
	PrID        *uuid.UUID
}

type ListRunsRow struct {
	ID            uuid.UUID
	AgentID       *uuid.UUID
	AgentName     *string
	Provider      *string
	Model         *string
	Status        *string
	Error         *string
	DurationMs    *int32
	TokensIn      *int32
	TokensOut     *int32
	FindingsCount *int32
	Grounding     *string
	RanAt         time.Time
	Score         *int32
	Blockers      *int32
}

// A pull request's review runs of any status, newest first.
func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.WorkspaceID, arg.PrID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentName,
			&i.Provider,
			&i.Model,
			&i.Status,
			&i.Error,
			&i.DurationMs,
			&i.TokensIn,
			&i.TokensOut,
			&i.FindingsCount,
			&i.Grounding,
			&i.RanAt,
			&i.Score,
			&i.Blockers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullExists = `-- name: PullExists :one
SELECT EXISTS (SELECT 1 FROM pull_requests WHERE workspace_id = $1 AND id = $2)
`

type PullExistsParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) PullExists(ctx context.Context, arg PullExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pullExists, arg.WorkspaceID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
