// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews_write.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const decideFinding = `-- name: DecideFinding :one
UPDATE findings f
SET accepted_at = $1, dismissed_at = $2
FROM reviews r, pull_requests p
WHERE f.id = $3 AND r.id = f.review_id AND p.id = r.pr_id AND p.workspace_id = $4
RETURNING f.id, f.review_id, f.file, f.start_line, f.end_line, f.severity, f.category, f.title, f.rationale, f.suggestion, f.confidence, f.kind, f.trifecta_components, f.accepted_at, f.dismissed_at
`

type DecideFindingParams struct {
	AcceptedAt  *time.Time
	DismissedAt *time.Time
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Records the user's decision on a finding: accepted_at or dismissed_at is
// set and the other cleared. Only a finding of a pull request in the
// workspace matches.
func (q *Queries) DecideFinding(ctx context.Context, arg DecideFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, decideFinding,
		arg.AcceptedAt,
		arg.DismissedAt,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.File,
		&i.StartLine,
		&i.EndLine,
		&i.Severity,
		&i.Category,
		&i.Title,
		&i.Rationale,
		&i.Suggestion,
		&i.Confidence,
		&i.Kind,
		&i.TrifectaComponents,
		&i.AcceptedAt,
		&i.DismissedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :execrows
DELETE FROM reviews WHERE workspace_id = $1 AND id = $2
`

type DeleteReviewParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// Deletes a review; its findings go with it (ON DELETE CASCADE).
func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReview, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRun = `-- name: DeleteRun :execrows
WITH deleted_reviews AS (
    DELETE FROM reviews r WHERE r.workspace_id = $1 AND r.run_id = $2
)
DELETE FROM agent_runs a WHERE a.workspace_id = $1 AND a.id = $2
`

type DeleteRunParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// Deletes a run, its trace (ON DELETE CASCADE) and the review it produced,
// in one statement. reviews.run_id has no foreign key, so the review must be
// deleted by hand. The count is of runs deleted.
func (q *Queries) DeleteRun(ctx context.Context, arg DeleteRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRun, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
