// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs_write.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const cancelRun = `-- name: CancelRun :execrows
UPDATE agent_runs SET status = 'cancelled'
WHERE workspace_id = $1 AND id = $2 AND status = 'running'
`

type CancelRunParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// Marks a running run of the workspace cancelled.
func (q *Queries) CancelRun(ctx context.Context, arg CancelRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRun, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRun = `-- name: CreateRun :one
INSERT INTO agent_runs (workspace_id, agent_id, pr_id, provider, model, status, source)
VALUES ($1, $2, $3, $4, $5, 'running', 'local')
RETURNING id
`

type CreateRunParams struct {
	WorkspaceID uuid.UUID
	AgentID     *uuid.UUID
	PrID        *uuid.UUID
	Provider    *string
	Model       *string
}

// A run of an agent on a pull request, running from now.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.WorkspaceID,
		arg.AgentID,
		arg.PrID,
		arg.Provider,
		arg.Model,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const enabledAgents = `-- name: EnabledAgents :many
SELECT id, workspace_id, name, description, provider, model, system_prompt, output_schema, enabled, version, created_by, created_at, strategy, ci_fail_on, repo_intel FROM agents WHERE workspace_id = $1 AND enabled ORDER BY created_at, id
`

// The workspace's agents that are on, oldest first.
func (q *Queries) EnabledAgents(ctx context.Context, workspaceID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, enabledAgents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Model,
			&i.SystemPrompt,
			&i.OutputSchema,
			&i.Enabled,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Strategy,
			&i.CiFailOn,
			&i.RepoIntel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failStaleRuns = `-- name: FailStaleRuns :execrows
UPDATE agent_runs SET status = 'failed' WHERE status = 'running'
`

// At startup: runs still marked running were left by a server that stopped.
func (q *Queries) FailStaleRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRun = `-- name: FinishRun :exec
UPDATE agent_runs
SET status = $1, duration_ms = $2, tokens_in = $3, tokens_out = $4,
    findings_count = $5, grounding = $6, score = $7,
    blockers = $8, error = $9
WHERE id = $10 AND status = 'running'
`

type FinishRunParams struct {
	Status        *string
	DurationMs    *int32
	TokensIn      *int32
	TokensOut     *int32
	FindingsCount *int32
	Grounding     *string
	Score         *int32
	Blockers      *int32
	Error         *string
	ID            uuid.UUID
}

// Records how a run ended, unless it isn't running any more: a cancelled
// run stays cancelled.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.Exec(ctx, finishRun,
		arg.Status,
		arg.DurationMs,
		arg.TokensIn,
		arg.TokensOut,
		arg.FindingsCount,
		arg.Grounding,
		arg.Score,
		arg.Blockers,
		arg.Error,
		arg.ID,
	)
	return err
}

const insertFinding = `-- name: InsertFinding :exec
INSERT INTO findings (review_id, file, start_line, end_line, severity, category, title,
                      rationale, suggestion, confidence, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertFindingParams struct {
	ReviewID   uuid.UUID
	File       string
	StartLine  int32
	EndLine    int32
	Severity   string
	Category   string
	Title      string
	Rationale  string
	Suggestion *string
	Confidence float64
	Kind       string
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) error {
	_, err := q.db.Exec(ctx, insertFinding,
		arg.ReviewID,
		arg.File,
		arg.StartLine,
		arg.EndLine,
		arg.Severity,
		arg.Category,
		arg.Title,
		arg.Rationale,
		arg.Suggestion,
		arg.Confidence,
		arg.Kind,
	)
	return err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (workspace_id, pr_id, agent_id, run_id, kind, verdict, summary, score, model)
VALUES ($1, $2, $3, $4, 'review', $5, $6, $7, $8)
RETURNING id
`

type InsertReviewParams struct {
	WorkspaceID uuid.UUID
	PrID        uuid.UUID
	AgentID     *uuid.UUID
	RunID       *uuid.UUID
	Verdict     *string
	Summary     *string
	Score       *int32
	Model       *string
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.WorkspaceID,
		arg.PrID,
		arg.AgentID,
		arg.RunID,
		arg.Verdict,
		arg.Summary,
		arg.Score,
		arg.Model,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockRunningRun = `-- name: LockRunningRun :one
SELECT id FROM agent_runs WHERE id = $1 AND status = 'running' FOR UPDATE
`

// The run, locked until the transaction ends, if it is still running: not
// cancelled or deleted meanwhile.
func (q *Queries) LockRunningRun(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockRunningRun, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const markReviewed = `-- name: MarkReviewed :exec
UPDATE pull_requests SET last_reviewed_sha = $2 WHERE id = $1
`

type MarkReviewedParams struct {
	ID              uuid.UUID
	LastReviewedSha *string
}

// Records the commit a review ran against, so the list can tell whether new
// commits came since.
func (q *Queries) MarkReviewed(ctx context.Context, arg MarkReviewedParams) error {
	_, err := q.db.Exec(ctx, markReviewed, arg.ID, arg.LastReviewedSha)
	return err
}

const saveTrace = `-- name: SaveTrace :exec
INSERT INTO run_traces (run_id, trace) VALUES ($1, $2)
ON CONFLICT (run_id) DO UPDATE SET trace = EXCLUDED.trace
`

type SaveTraceParams struct {
	RunID uuid.UUID
	Trace []byte
}

func (q *Queries) SaveTrace(ctx context.Context, arg SaveTraceParams) error {
	_, err := q.db.Exec(ctx, saveTrace, arg.RunID, arg.Trace)
	return err
}
