// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const addOwner = `-- name: AddOwner :exec
INSERT INTO workspace_members (workspace_id, user_id, role) VALUES ($1, $2, 'owner')
ON CONFLICT DO NOTHING
`

type AddOwnerParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) AddOwner(ctx context.Context, arg AddOwnerParams) error {
	_, err := q.db.Exec(ctx, addOwner, arg.WorkspaceID, arg.UserID)
	return err
}

const agentNamed = `-- name: AgentNamed :one
SELECT EXISTS (SELECT 1 FROM agents WHERE workspace_id = $1 AND name = $2)
`

type AgentNamedParams struct {
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) AgentNamed(ctx context.Context, arg AgentNamedParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentNamed, arg.WorkspaceID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertSeedPull = `-- name: InsertSeedPull :one
INSERT INTO pull_requests (workspace_id, repo_id, number, title, author, branch, base, head_sha,
                           additions, deletions, files_count, status, body)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type InsertSeedPullParams struct {
	WorkspaceID uuid.UUID
	RepoID      uuid.UUID
	Number      int32
	Title       string
	Author      string
	Branch      string
	Base        string
	HeadSha     string
	Additions   int32
	Deletions   int32
	FilesCount  int32
	Status      string
	Body        *string
}

func (q *Queries) InsertSeedPull(ctx context.Context, arg InsertSeedPullParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSeedPull,
		arg.WorkspaceID,
		arg.RepoID,
		arg.Number,
		arg.Title,
		arg.Author,
		arg.Branch,
		arg.Base,
		arg.HeadSha,
		arg.Additions,
		arg.Deletions,
		arg.FilesCount,
		arg.Status,
		arg.Body,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSeedRepo = `-- name: InsertSeedRepo :one
INSERT INTO repos (workspace_id, owner, name, full_name, default_branch, created_by)
VALUES ($1, $2, $3, $4, 'main', $5)
RETURNING id
`

type InsertSeedRepoParams struct {
	WorkspaceID uuid.UUID
	Owner       string
	Name        string
	FullName    string
	CreatedBy   *uuid.UUID
}

func (q *Queries) InsertSeedRepo(ctx context.Context, arg InsertSeedRepoParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSeedRepo,
		arg.WorkspaceID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, name) VALUES ($1, $2) RETURNING id
`

type InsertUserParams struct {
	Email string
	Name  string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Email, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertWorkspace = `-- name: InsertWorkspace :one
INSERT INTO workspaces (name) VALUES ($1) RETURNING id
`

func (q *Queries) InsertWorkspace(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertWorkspace, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockSeed = `-- name: LockSeed :exec
SELECT pg_advisory_xact_lock(hashtextextended('devdigest-seed', 0))
`

func (q *Queries) LockSeed(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSeed)
	return err
}

const seedPullExists = `-- name: SeedPullExists :one
SELECT EXISTS (SELECT 1 FROM pull_requests WHERE repo_id = $1 AND number = $2)
`

type SeedPullExistsParams struct {
	RepoID uuid.UUID
	Number int32
}

func (q *Queries) SeedPullExists(ctx context.Context, arg SeedPullExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, seedPullExists, arg.RepoID, arg.Number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const seedSetting = `-- name: SeedSetting :exec
INSERT INTO settings (workspace_id, user_id, key, value) VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, user_id, key) DO NOTHING
`

type SeedSettingParams struct {
	WorkspaceID uuid.UUID
	UserID      *uuid.UUID
	Key         string
	Value       []byte
}

// A default preference, unless the user has one.
func (q *Queries) SeedSetting(ctx context.Context, arg SeedSettingParams) error {
	_, err := q.db.Exec(ctx, seedSetting,
		arg.WorkspaceID,
		arg.UserID,
		arg.Key,
		arg.Value,
	)
	return err
}
