// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const listSettings = `-- name: ListSettings :many
SELECT key, value
FROM settings
WHERE workspace_id = $1
ORDER BY key, user_id NULLS FIRST
`

type ListSettingsRow struct {
	Key   string
	Value []byte
}

// The workspace's preferences. A key can have a workspace-wide row
// (user_id NULL) and per-user rows; the per-user rows come last, so they win
// when the caller folds the rows into one object.
func (q *Queries) ListSettings(ctx context.Context, workspaceID uuid.UUID) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettingsRow
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
