// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills_write.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (workspace_id, name, description, type, source, body, enabled, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1)
RETURNING id, workspace_id, name, description, type, source, body, enabled, version, evidence_files, created_at
`

type CreateSkillParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Description string
	Type        string
	Source      string
	Body        string
	Enabled     bool
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Source,
		arg.Body,
		arg.Enabled,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Source,
		&i.Body,
		&i.Enabled,
		&i.Version,
		&i.EvidenceFiles,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :execrows
DELETE FROM skills WHERE workspace_id = $1 AND id = $2
`

type DeleteSkillParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkill, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSkillVersionBody = `-- name: GetSkillVersionBody :one
SELECT body FROM skill_versions WHERE skill_id = $1 AND version = $2
`

type GetSkillVersionBodyParams struct {
	SkillID uuid.UUID
	Version int32
}

func (q *Queries) GetSkillVersionBody(ctx context.Context, arg GetSkillVersionBodyParams) (string, error) {
	row := q.db.QueryRow(ctx, getSkillVersionBody, arg.SkillID, arg.Version)
	var body string
	err := row.Scan(&body)
	return body, err
}

const insertSkillVersion = `-- name: InsertSkillVersion :exec
INSERT INTO skill_versions (skill_id, version, body, message) VALUES ($1, $2, $3, $4)
`

type InsertSkillVersionParams struct {
	SkillID uuid.UUID
	Version int32
	Body    string
	Message *string
}

func (q *Queries) InsertSkillVersion(ctx context.Context, arg InsertSkillVersionParams) error {
	_, err := q.db.Exec(ctx, insertSkillVersion,
		arg.SkillID,
		arg.Version,
		arg.Body,
		arg.Message,
	)
	return err
}

const lockSkill = `-- name: LockSkill :one
SELECT id, workspace_id, name, description, type, source, body, enabled, version, evidence_files, created_at FROM skills WHERE workspace_id = $1 AND id = $2 FOR UPDATE
`

type LockSkillParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

// The skill, locked until the transaction ends, so two updates can't both
// read the same version number.
func (q *Queries) LockSkill(ctx context.Context, arg LockSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, lockSkill, arg.WorkspaceID, arg.ID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Source,
		&i.Body,
		&i.Enabled,
		&i.Version,
		&i.EvidenceFiles,
		&i.CreatedAt,
	)
	return i, err
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET name = $2, description = $3, type = $4, body = $5, enabled = $6, version = $7
WHERE id = $1
RETURNING id, workspace_id, name, description, type, source, body, enabled, version, evidence_files, created_at
`

type UpdateSkillParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Type        string
	Body        string
	Enabled     bool
	Version     int32
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Body,
		arg.Enabled,
		arg.Version,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Source,
		&i.Body,
		&i.Enabled,
		&i.Version,
		&i.EvidenceFiles,
		&i.CreatedAt,
	)
	return i, err
}
