// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getSkill = `-- name: GetSkill :one
SELECT s.id, s.workspace_id, s.name, s.description, s.type, s.source, s.body, s.enabled, s.version, s.evidence_files, s.created_at,
       (SELECT count(*) FROM agent_skills l WHERE l.skill_id = s.id) AS agent_count
FROM skills s
WHERE s.workspace_id = $1 AND s.id = $2
`

type GetSkillParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

type GetSkillRow struct {
	Skill      Skill
	AgentCount int64
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (GetSkillRow, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.WorkspaceID, arg.ID)
	var i GetSkillRow
	err := row.Scan(
		&i.Skill.ID,
		&i.Skill.WorkspaceID,
		&i.Skill.Name,
		&i.Skill.Description,
		&i.Skill.Type,
		&i.Skill.Source,
		&i.Skill.Body,
		&i.Skill.Enabled,
		&i.Skill.Version,
		&i.Skill.EvidenceFiles,
		&i.Skill.CreatedAt,
		&i.AgentCount,
	)
	return i, err
}

const listSkillAgents = `-- name: ListSkillAgents :many
SELECT a.id, a.workspace_id, a.name, a.description, a.provider, a.model, a.system_prompt, a.output_schema, a.enabled, a.version, a.created_by, a.created_at, a.strategy, a.ci_fail_on, a.repo_intel
FROM agents a
JOIN agent_skills l ON l.agent_id = a.id
WHERE a.workspace_id = $1 AND l.skill_id = $2
ORDER BY a.created_at, a.id
`

type ListSkillAgentsParams struct {
	WorkspaceID uuid.UUID
	SkillID     uuid.UUID
}

// The agents using a skill, oldest first.
func (q *Queries) ListSkillAgents(ctx context.Context, arg ListSkillAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listSkillAgents, arg.WorkspaceID, arg.SkillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Model,
			&i.SystemPrompt,
			&i.OutputSchema,
			&i.Enabled,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Strategy,
			&i.CiFailOn,
			&i.RepoIntel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillVersions = `-- name: ListSkillVersions :many
SELECT skill_id, version, body, created_at, message FROM skill_versions WHERE skill_id = $1 ORDER BY version DESC
`

// A skill's body history, newest first.
func (q *Queries) ListSkillVersions(ctx context.Context, skillID uuid.UUID) ([]SkillVersion, error) {
	rows, err := q.db.Query(ctx, listSkillVersions, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillVersion
	for rows.Next() {
		var i SkillVersion
		if err := rows.Scan(
			&i.SkillID,
			&i.Version,
			&i.Body,
			&i.CreatedAt,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT s.id, s.workspace_id, s.name, s.description, s.type, s.source, s.body, s.enabled, s.version, s.evidence_files, s.created_at,
       (SELECT count(*) FROM agent_skills l WHERE l.skill_id = s.id) AS agent_count
FROM skills s
WHERE s.workspace_id = $1
ORDER BY s.created_at, s.id
`

type ListSkillsRow struct {
	Skill      Skill
	AgentCount int64
}

// Oldest first, like agents, each with the number of agents using it.
func (q *Queries) ListSkills(ctx context.Context, workspaceID uuid.UUID) ([]ListSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSkills, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillsRow
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.Skill.ID,
			&i.Skill.WorkspaceID,
			&i.Skill.Name,
			&i.Skill.Description,
			&i.Skill.Type,
			&i.Skill.Source,
			&i.Skill.Body,
			&i.Skill.Enabled,
			&i.Skill.Version,
			&i.Skill.EvidenceFiles,
			&i.Skill.CreatedAt,
			&i.AgentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skillExists = `-- name: SkillExists :one
SELECT EXISTS (SELECT 1 FROM skills WHERE workspace_id = $1 AND id = $2)
`

type SkillExistsParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SkillExists(ctx context.Context, arg SkillExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, skillExists, arg.WorkspaceID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
